//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.15 at 11:31:42 AM EDT 
//


package simplenlg.xmlrealiser.wrapper;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the simplenlg.xmlrealiser.wrapper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("http://code.google.com/p/simplenlg/schemas/version1", "Document");
    private final static QName _Tests_QNAME = new QName("http://code.google.com/p/simplenlg/schemas/TestSet", "Tests");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: simplenlg.xmlrealiser.wrapper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdjPhraseSpec }
     * 
     */
    public AdjPhraseSpec createAdjPhraseSpec() {
        return new AdjPhraseSpec();
    }

    /**
     * Create an instance of {@link StringElement }
     * 
     */
    public StringElement createStringElement() {
        return new StringElement();
    }

    /**
     * Create an instance of {@link VPPhraseSpec }
     * 
     */
    public VPPhraseSpec createVPPhraseSpec() {
        return new VPPhraseSpec();
    }

    /**
     * Create an instance of {@link TestSet }
     * 
     */
    public TestSet createTestSet() {
        return new TestSet();
    }

    /**
     * Create an instance of {@link PPPhraseSpec }
     * 
     */
    public PPPhraseSpec createPPPhraseSpec() {
        return new PPPhraseSpec();
    }

    /**
     * Create an instance of {@link WordElement }
     * 
     */
    public WordElement createWordElement() {
        return new WordElement();
    }

    /**
     * Create an instance of {@link AdvPhraseSpec }
     * 
     */
    public AdvPhraseSpec createAdvPhraseSpec() {
        return new AdvPhraseSpec();
    }

    /**
     * Create an instance of {@link CoordinatedPhraseElement }
     * 
     */
    public CoordinatedPhraseElement createCoordinatedPhraseElement() {
        return new CoordinatedPhraseElement();
    }

    /**
     * Create an instance of {@link NPPhraseSpec }
     * 
     */
    public NPPhraseSpec createNPPhraseSpec() {
        return new NPPhraseSpec();
    }

    /**
     * Create an instance of {@link SPhraseSpec }
     * 
     */
    public SPhraseSpec createSPhraseSpec() {
        return new SPhraseSpec();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link DocumentElement }
     * 
     */
    public DocumentElement createDocumentElement() {
        return new DocumentElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/simplenlg/schemas/version1", name = "Document")
    public JAXBElement<DocumentElement> createDocument(DocumentElement value) {
        return new JAXBElement<DocumentElement>(_Document_QNAME, DocumentElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/simplenlg/schemas/TestSet", name = "Tests")
    public JAXBElement<TestSet> createTests(TestSet value) {
        return new JAXBElement<TestSet>(_Tests_QNAME, TestSet.class, null, value);
    }

}
